💚 Remove JRuby 9.3 from CI
It will never pass, since JRuby 9.3 isn't getting any more fixes:
NoMethodError: undefined method `resolve_feature_path' for #<Array:0x566f4659>
    <main> at /home/runner/.rubies/jruby-9.3.15.0/lib/ruby/gems/shared/gems/erb-4.0.4-java/lib/erb/util.rb:9